version: "3"

services:
  app:
    container_name: autosub_app
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./src:/app/src
      - ./app.py:/app/app.py
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=autosub
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      - ADMIN_EMAIL=admin@example.com
      - SALT=c89f7d83b48a42e99addf3fb9a10c2a4
      - FLASK_SECRET_KEY=e3ac3d46-20e1-4a43-8c8f-230e142a3df4
      - UPLOAD_FOLDER=/app/uploads
      - ALLOWED_EXTENSIONS=mp4,mov,avi,mkv
    depends_on:
      - db

  db:
    container_name: autosub_db
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=autosub
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
